---
ABC:

  # initial seed to generate the random seed numbers for the simulations
  seed: 12345  # Do not change this
  nseed: 1e6  # num of seeds, must be bigger than the number of simulations
  # whether to ask for the parameter estimation of the pods; leave it True
  do_parameter_estimation: True
  # whether to visualize the parameter estimation, model choice etc.
  do_visualisation: True
  # the number of rows for the generated seeds, will be used for the independent
  # loci; for Arabidopsis thaliana, the first five rows would mark the seeds for
  # the simulation of 5 independent loci mimicking 5 chromosomes.
  locdim: 20
  # will consequentially execute this number of simulations. This helps to
  # reduce computational load to create the dag
  jobluster_simulations: 100

  # id of the first simulation for this workflow. this is the index that is used
  # to pick the random seed number 
  first_simid: 0

  simulations:
    nsim: 20000  # number of simulations for the ABC
    # number of sample haplotypes to simulate (and to observe for athaliana)
    nsam: 20
    nloci: 5  # number of independent loci (mimicking chromosomes)
    locuslen: 1e6  # length of each locus
    mutrate: 1e-8  # 6.95e-9  # mutation rate
    recrate: 1e-8  # 3.6e-8  # recombination rate
    # duration of initial simulation model ("discrete time WF"); see msprime
    # documentation
    dtwf: 1000

  # combinations of summary statistics to be used for the model choice and
  # parameter estimate
  sumstats:
    - SFS/LD
    - TM_WIN
    - SFS/LD/TM_WIN

  # specifications how to calculate the summarizing statistics
  sumstats_specs:
    # based on this seed, we choose which haplotype we use for calculating the
    # summarizing statistics, as dtwf-models do only support diploid individuals
    seed: 39868
    seed_athal: 55578
    run_masked: True
    SFS:
      polarised: False
    LD:
      # number of random SNPs to take into account for the LD calculation
      npos: 1e3
      breaks:  # which breakpoints to use for discretization
        - 1
        - 6105.472
        - 11379.62
        - 21209.786
        - 39531.638
        - 73680.63
        - 137328.871
        - 255958.978
        - 477066.461
        - 889175.328
        - 1657280.126
        - 3088904.21
        - 5757221.77
        - 10730537.517
        - 20000000
    TM_WIN:
      winsize: 1e4  # window size of the sliding non-overlapping window
      classes: 20  # number of discretized bins
      # how to calculate the discretization for tm_win, breaks mode can take one
      # of three values: "pod", "athal", "expected"; "pod" means to calculate
      # the breakpoints on the statistics of the first pod; "athal" means to
      # calculate the breakpoints on the statistics of the first provided athal
      # population defined in this 
      # config["ABC"]["athaliana"]["observations"]["treeseq_1001"]["popid"]
      # calculate boundaries based on the first pods theoretical expectation
      # similar to how it is done in the MSMC paper
      breaks_mode: expected
      # from which population to calc the breakpoints for discretization if
      # breaks_mode is athal
      which_pop_if_athal: CEU
      # when calculating the expected coalescent times for discretization, we
      # use Schiffels, Durbin 2014 formula, but the times are rescaled in 2N0,
      # thus we need to translate them into SNPs, for which we need a value;
      # usually this should be an estimate based on theta Watterson and compare
      # to a population size that we want to inspect
      two_N_zero_if_expected: 55304  # `snakemake -j 1 theta_watterson_region`
      two_N_zero_if_expected_seed: 6839  # For the simulations; do not change

  model:
    # quatrupels: min, max, numeric type (float, int), distribution type
    # (uniform, loguniform)
    priors:
      - [1e4, 2e5, int, loguniform]  # param 1: pop size
      - [0.5, 1, float, uniform]  # param 2: present selfing rate
      - [0, 0.2, float, uniform]  # param 3: ancestral selfing rate
      - [0.9e3, 5e5, int, loguniform]  # param 4: time of transition

  alternative_model:
    # wether to as for the the alternative model to be simulated
    do_model_choice: True
    # initial seed to generate the random seed numbers for the simulations
    seed: 85426  # Do not change this
    nsim: 20000  # number of simulations for the alternative model in the ABC
    # id of the first simulation for this workflow. this is the index that is used
    # to pick the random seed number 
    first_simid: 0
    # will consequentially execute this number of simulations. This helps to
    # reduce computational load to create the dag
    jobluster_simulations: 100

    # quatrupels: min, max, numeric type (float, int), distribution type
    # (uniform, loguniform)
    priors:
      - [1e4, 2e5, int, loguniform]  # param 1: present pop size
      - [0.8, 1, float, uniform]  # param 2: constant selfing rate
      - [1e4, 2e5, int, loguniform]  # param 3: ancestral pop size
      - [0.8e4, 5e5, int, loguniform]  # param 4: time of pop size change

  # analysis of performance 
  performance:
    nsim: 100  # number of simulations per pseudo-observed data set
    tolerance_estimates: [500]  # number of accepted simulations
    tolerance_model_choice: [500]  # number of accepted simulations
    # probably should not be same as sim seed; do not change this
    pods_seed: 23456
    poddim: 500  # max number of pod sets; important for seed generation
    pods:
      - [4e4,   4e4,   4e4,   4e4,  4e4,  4e4,  4e4,  4e4]  # param 1 for each pods, respectively
      - [0.99,  0.99,  0.99,  0.99, 0.99, 0.99, 0.99, 0.99]  # param 2 for each pods, respectively
      - [0.1,   0.1,   0.1,   0.1,  0.1,  0.1,  0.1,  0.1]  # param 3 for each pods, respectively
      - [2e4,   1e4,   4e4,   1e5,  5e5,  1e3,  2e3,  5e3]  # param 4 for each pods, respectively
    pls: [20]
    pls_max: 33  # maximal pls to be calculated for transformer
    # regression used for parameter estimate as defined in the r-abc package
    regression: ["loclinear"]

  # parameter estimation on Arabidopsis thaliana using the six-parameter model
  athaliana:
    do_thaliana: False
    # whehter to visualize the parameter estimation of Arabidopsis thaliana
    do_visualisation: True
    # initial seed to generate the random seed numbers for the simulations
    seed: 91424  # Do not change this
    nseed: 1e6  # num of seeds, must be bigger than the number of simulations
    # the number of rows for the generated seeds, will be used for the independent
    # loci; for Arabidopsis thaliana, the first five rows would mark the seeds for
    # the simulation of 5 independent loci mimicking 5 chromosomes.
    locdim: 20
    # will consequentially execute this number of simulations. This helps to
    # reduce computational load to create the dag
    jobluster_simulations: 250

    # quatrupels: min, max, numeric type (float, int), distribution type
    # (uniform, loguniform)
    priors:
      - [1e3, 1e5, int, loguniform]  # param 1: present pop size
      - [1e3, 1e5, int, loguniform]  # param 2: ancestral pop size
      - [1e2, 5e5, int, uniform]  # param 4: time of pop size change
      - [0.8, 1, float, uniform]  # param 3: present selfing rate
      - [0, 0.2, float, uniform]  # param 4: ancestral selfing rate
      - [1e2, 5e5, int, uniform]  # param 5: time of transition

    observations:
      # maximum number of observations from the population
      num_observations: 1000
      # initial seed to generate the random seed numbers for the simulations
      seed: 97636  # Do not change this
      treeseq_1001:
        # path to the full 1001 genomes tree sequence
        path: "resources/athal/1135_tsinfer_tree_sequence.ts"
        chrom_multiplier: 1e8  # start of chromosomal position multiplier
        # The region should be chosen in a way that the mask file indexes the
        # correct exonic regions
        chosen_region:  # must provide one per chromosome/locus
          - [6_500_000,   7_500_000]  # start/end for chromosome 1
          - [16_000_000, 17_000_000]  # start/end for chromosome 2
          - [6_000_000,   7_000_000]  # start/end for chromosome 3
          - [13_000_000, 14_000_000]  # start/end for chromosome 4
          - [1_500_000,   2_500_000]  # start/end for chromosome 5
        # chr/start/end after Charles Underwood (methylation based)
        whole_gemome_approach:
          - [1,          0,   11_420_000]  # North 1
          - [1, 18_270_001,   30_427_671]  # South 1
          - [2,          0,      910_000]  # North 2
          - [2,  7_320_001,   19_698_289]  # South 2
          - [3,          0,   10_390_000]  # North 3
          - [3, 16_730_001,   23_459_830]  # South 3
          - [4,          0,    1_070_000]  # North 4
          - [4,  6_630_001,   18_585_056]  # South 4
          - [5,          0,    8_890_000]  # North 5
          - [5, 15_550_001,   26_975_451]  # South 5; end 26_975_502, but no sites
        whole_genome_approach_num_observations: 20  # LD calculation is very slow
        popid:  # the files contain the sample ids according to the 1001 genomes
          CEU:  # this name will be the population id
            path: "resources/athal/sample_populations/individual.identifier_list_CEU.txt"
          IBnr:  # this name will be the population id
            path: "resources/athal/sample_populations/individual.identifier_list_IBnr.txt"
          Relicts:  # this name will be the population id
            path: "resources/athal/sample_populations/individual.identifier_list_Relicts.txt"

